### PR TITLE
fix: increase lookups limits

### LINKED ISSUE #51: Not found tz for coords: 53.3357911103805, 83.6486383092998
Get error for: 
[/tz/53.3357911103805/83.6486383092998](http://localhost:2004/tz/53.3357911103805/83.6486383092998)

But [/tz/53/83](http://localhost:2004/tz/53.3357911103805/83.6486383092998) OK. 

Why?

### PR DESCRIPTION
**Pull request by noandrea**
fix #51

### CODE REVIEW

File: db/rtree.go [hunk 1]
```diff
@@ -13,8 +13,9 @@ import (
 )
 
 type Geo2TzRTreeIndex struct {
-	land rtree.RTreeG[timezoneGeo]
-	sea  rtree.RTreeG[timezoneGeo]
+	max_lookups int
+	land        rtree.RTreeG[timezoneGeo]
```
Comment (J2085isa) [inline db/rtree.go:17]: Jar_('nsjfjdbw_;'nxjdbs€=¥℅¥=©℅¢*;"+$-#€¢÷÷×®©%

**Review by J2085isa — APPROVED** [review]

File: db/testdata/coordinates.json [hunk 2]
```diff
@@ -146,5 +146,7 @@
   { "lat": 39.9042, "lon": 116.4074, "tz": "Asia/Shanghai" },
   { "lat": 48.8566, "lon": 2.3522, "tz": "Europe/Paris" },
   { "lat": 31.2304, "lon": 121.4737, "tz": "Asia/Shanghai" },
-  { "lat": 52.3676, "lon": 4.9041, "tz": "Europe/Amsterdam" }
+  { "lat": 52.3676, "lon": 4.9041, "tz": "Europe/Amsterdam" },
+  { "lat": 53, "lon": 83, "tz": "Asia/Barnaul" },
+  { "lat": 53.3357911103805, "lon": 83.6486383092998, "tz": "Asia/Barnaul" }
```
Comment (J2085isa) [inline db/testdata/coordinates.json:151]: México jose isaias Álvarez Ramírez

**Review by J2085isa — APPROVED** [review]
